### ISSUE TITLE
InventoryClickEvent on IntelligentItem doesn't work

### ISSUE THREAD

**Issue by LudovicAns** [Rysefoxx/RyseInventory#30] opened 2022-10-12 17:26 UTC
**Describe the bug**
When using pagination, inventoryClickEvent on IntelligentItem doesn't work.

**To Reproduce**
1. Create an inventory using pagination.
2. Add some IntelligentItem with action on inventoryClickEvent.
3. Try IG

**Expected behavior**
Working inventoryclickevent on IntelligentItem.

**Code (Optional)**
```
public class STCInventoryProvider implements InventoryProvider {

    private final ConfigurationManager cm;
    private final RyseInventory ryseInventory;

    public STCInventoryProvider(ConfigurationManager cm) {
        this.cm = cm;

        ryseInventory = RyseInventory.builder()
                .provider(this)
                .size(9*6)
                .manager(TerraWildAPI.getINSTANCE().getInventoryManager())
                .title("Staff Chat")
                .build(TWStaffChat.getINSTANCE());
    }

    @Override
    public void init(Player player, InventoryContents contents) {
        final FileConfiguration cfg = cm.getConfigurationFile("config.yml");
        final ConfigurationSection messages = cfg.getConfigurationSection("messages");

        if (messages == null) return;

        final Pagination pagination = contents.pagination();
        pagination.iterator(slotIterator());

        for (String key : messages.getKeys(false)) {
            final ConfigurationSection messageSection = messages.getConfigurationSection(key);
            if (messageSection == null) return;

            final YAMLParser yamlParser = new YAMLParser(cfg);
            final ItemStack itemStack = yamlParser.getItemStack(
                    messageSection.getCurrentPath() + ".item",
                    new ItemBuilder(Material.BARRIER)
                            .setAmount(1)
                            .setDisplayName(new ColoredText("&cErreur de configuration de l'item !").buildComponent())
                            .getItemStack()
            );
            assert itemStack != null;

            final String message = messageSection.getString("message");

            pagination.addItem(IntelligentItem.of(itemStack, inventoryClickEvent -> {
                inventoryClickEvent.getWhoClicked().sendMessage("test");
            }));
        }
    }

    private SlotIterator slotIterator() {
        List<Integer> blacklist = new ArrayList<>(Arrays.asList(
                0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53
        ));

        return SlotIterator
                .builder()
                .startPosition(10)
                .endPosition(43)
                .blackList(blacklist)
                .type(SlotIterator.SlotIteratorType.HORIZONTAL)
                .build();
    }

    public RyseInventory getRyseInventory() {
        return ryseInventory;
    }
}

```

**Comment by Rysefoxx** [comment] 2022-10-13 16:05
Duplicate of [26](https://github.com/Rysefoxx/RyseInventory/issues/26)

**Closed by Rysefoxx** 2022-10-13 16:05 UTC
Labels: duplicate
