### ISSUE TITLE
Error java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Lemar98** [Rysefoxx/RyseInventory#17] opened 2022-09-24 14:42 UTC
My task is to put a set of my items in a custom inventory, and I also want to make an improvement for the inventory: so that at N level the player has the number of rows in the inventory revealed. Let's say Player1 has 8 rows unlocked, which means he has the first full page and the second page with two rows.

In the latest version of your API (1.5.0), the page, for some reason, teaches itself (maybe it's in my code, I'm attaching it).
https://pastebin.com/8rUCidK8

Player1 has 52 stacks of earth in the inventory (which completely fills the first page of the inventory) and so that the player can open the page before setting the items in the pagination list, I add a regular stone to it.

But when I try to open inventory, the console tells me https://pastebin.com/mu2X8GiT

What am I doing wrong?

**Comment by Rysefoxx** [comment] 2022-09-24 16:05
If you use pagination and add items via Pagination#setItems or Pagination#addItem, they will initially get the slot -1. Because at that time there is no slot for these items. The items you then define via Pagination#setItems or Pagination#addItem get a slot based on your SlotIterator by the algorithm.

Your problem seems to be that it opens the inventory (the items you set via Pagination then all have -1), but the items then get no slot assigned. I'm currently trying to recreate your problem but without success. It works for me.

Translated with www.DeepL.com/Translator (free version)

**Comment by Rysefoxx** [comment] 2022-09-24 16:06
If you use pagination and add items via Pagination#setItems or Pagination#addItem, they will initially get the slot -1. Because at that time there is no slot for these items. The items you then define via Pagination#setItems or Pagination#addItem get a slot based on your SlotIterator by the algorithm.

Your problem seems to be that it opens the inventory (the items you set via Pagination then all have -1), but the items then get no slot assigned. I'm currently trying to recreate your problem but without success. It works for me.

**Comment by Lemar98** [comment] 2022-09-24 17:43
The problem solved itself, I didn't even touch anything, lol
But there was another problem...
The console tells me this https://pastebin.com/Hdm226y8

As I understand it, the point is that my size variable is 54, so the first if block in the code fires and the plugin tries to insert navigation items on slots 45 and 53, but for some reason your plugin thinks that these slots should not be, although if I print to the console the number of the next page, it will be 2. But if I print to the console pagination#inventory()#getSize() it shows me -1. Weird.

**Comment by Rysefoxx** [comment] 2022-09-24 17:57
So Pagination#inventory#getSize will most likely return -1 because you are using the #rows(Page) method. If you would use the #rows(Integer) method, getSize would return the value accordingly. But I will remove getSize in the next update, that's what #size is for. The method #size returned if you used #rows(Page), the size of the current page. If you use #rows(Integer), the size for all inventories.

For example, you have defined page 1 = 3 rows and page 2 = 6 rows. Now if the player has the 2 page open and you call #size, you will get back 54. If the player is on the 1 side it will return 27.

But if you say all sides have 6 rows, #size will return 54.

Translated with www.DeepL.com/Translator (free version)

**Comment by Rysefoxx** [comment] 2022-09-24 17:57
So Pagination#inventory#getSize will most likely return -1 because you are using the #rows(Page) method. If you would use the #rows(Integer) method, getSize would return the value accordingly. But I will remove getSize in the next update, that's what #size is for. The method #size returned if you used #rows(Page), the size of the current page. If you use #rows(Integer), the size for all inventories.

For example, you have defined page 1 = 3 rows and page 2 = 6 rows. Now if the player has the 2 page open and you call #size, you will get back 54. If the player is on the 1 side it will return 27.

But if you say all sides have 6 rows, #size will return 54.

**Comment by Lemar98** [comment] 2022-09-24 18:07
And how can you check which page the player has open and what size it has (how many rows)?

**Comment by Rysefoxx** [comment] 2022-09-24 18:16
1) So you can get the current page of the player via Pagination#page. (Note that when you call Pagination#page it will be counted +1).

2) You can call #size(InventoryContents) as I said, it will give you the current size. To get the rows you can simply divide by 9.

**Comment by Lemar98** [comment] 2022-09-24 19:36
After I changed the algorithm for calculating the size, my code began to show me an error like in update 1.4.9: There is no page with the number 2

my current code is: https://pastebin.com/CymfGuiS

**Comment by Rysefoxx** [comment] 2022-09-24 20:38
This is probably because you are calling pagination.page(). As said before when you call pagination.page() the current page is added +1. So page 0 is page 1.

But what exactly are you trying to do with the following code?
int size = pagination.page(pagination.page()).inventory().size(contents);

Just say int size = pagination.inventory().size(contents);

**Comment by Lemar98** [comment] 2022-09-24 21:50
It looks like it worked, thanks.
But there was another problem...

When a player has 52 stacks of something, I add 2 new ItemStacks to him so that he has access to a new page. But when the player opens the second page, the items seem to dupe! Both rows are again filled with blocks of earth that the player had on the first page

my code: https://pastebin.com/YFwygzT5

first page: 
![image](https://user-images.githubusercontent.com/45980309/192119830-057749fd-2c11-4224-8f36-239a5e1a29b6.png)
second page: 
![image](https://user-images.githubusercontent.com/45980309/192119842-ba0f6152-ca78-435b-99f4-075db53b7ceb.png)

Why is this even happening? Or maybe there is some way to give the player access to the next page if the first page is filled with 52 items?

**Comment by Rysefoxx** [comment] 2022-09-24 22:17
Hm sure you don't have more grass in the list which then gets shipped to the 2 page?

You can't directly say that the player has access to the next page when the previous inventory is full.

There is a method #fixedPageSize(), with which you can set a fixed number of pages. So he can also open pages that are empty.
The problem is still currently that it is hardcoded. If you say 1x in the builder the fixedPageSize, you can't change it afterwards. This will only come to the update 1.5.1.

Translated with www.DeepL.com/Translator (free version)

**Comment by Rysefoxx** [comment] 2022-09-24 22:18
Hm sure you don't have more grass in the list which then gets shipped to the 2 page?

You can't directly say that the player has access to the next page when the previous inventory is full.

There is a method #fixedPageSize(), with which you can set a fixed number of pages. So he can also open pages that are empty.
The problem is still currently that it is hardcoded. If you say 1x in the builder the fixedPageSize, you can't change it afterwards. This will only come to the update 1.5.1.

**Comment by Lemar98** [comment] 2022-09-24 22:49
Yes, I'm pretty sure there are only 52 items on my list. Every time the "init" method is called after adding two random items to the list, I print the size of my list to the console. It always returns me 54

**Comment by Rysefoxx** [comment] 2022-09-25 08:16
Hm funny. Do you have any information on how I can best reproduce this situation? Because the problem does not exist with me.

**Comment by Lemar98** [comment] 2022-09-25 19:19
Take my code and try it yourself. Screenshots attached
![image](https://user-images.githubusercontent.com/45980309/192161237-fff17d0b-569b-4fe3-a047-27f92f4c5d93.png)
![image](https://user-images.githubusercontent.com/45980309/192161245-92f16868-9e3b-446e-905d-e17ec0a3033f.png)

https://pastebin.com/J21zjqXr

**Comment by Rysefoxx** [comment] 2022-09-26 17:56
I found out the error. It seems to be a common mistake. When you open the inventory, a slot is calculated for each item. Until then everything works without you noticing it. If you go to the next page, the slots are calculated for the items again. But the error occurs with this calculation.

We have 2 different sizes. 1x 9*6 and 1x 9*2. That means we calculate 9*2 we come to 18 and the -1 because we start at 0. That means we have 17 slots on page 2. But the problem is that my algorithm does not get along with the fact that the pages have different sizes. So now it calculates the slots for the first page, but only goes up to slot 17, because the current inventory we have open has only 17 slots. From slot 18 on the first page he breaks off, because he thinks the inventory has only 17 slots, goes to page 2 and sets from there the items that you also have on page 1.

Very confusing :)

**Comment by Lemar98** [comment] 2022-09-26 22:01
Hardcode ;D

**Comment by Rysefoxx** [comment] 2022-10-01 12:05
Okay, I did some testing and found that it wasn't a bug in my algorithm after all, but a bug in your code.

Here is a picture of the error:
![image](https://user-images.githubusercontent.com/59345967/193408667-6a4ccf5f-099b-4f22-9880-9296f5b14fb6.png)

In this image you say pagination.inventory().size(contents). That means you get the current size of the inventory.  On page 1 it is 9*6 and on page 2 9*2.

And there is the error. You go to page 2, in the int size variable is now the value 18. In the SlotIterator you say .endPosition(size == 54 ? size - 1 : size). The last slot is 17 and so it stops at slot 17 and goes to the next page.

**Comment by Lemar98** [comment] 2022-10-02 12:19
1. When I remove the ".endPosition" line of code, everything works perfectly, but I can't remove it completely, because I need the SlotIterator to ignore some slots.

I don't understand why the error is in my code, could you explain it in more detail? I can't calculate to what position the SlotIterator should work without getting the size of the current page!

Right now my code looks like this: https://pastebin.com/D30K4NyM
I changed my task a little and now I need to display a certain fill in the entire line at the end of the page. To do this, in #endPosition of the SlotIterator I specify size - 9, thereby literally telling your algorithm "Fill the entire page with items except the last line", and this again leads to the fact that the items on the last page are repeated!

2. Also I noticed another "bug" (I don't know if it concerns your code or mine). This bug can be tested with the code I have attached above. For some reason, the item that should start the next page just disappears and the next item appears instead. I will try to explain it in the pictures below, as it is quite difficult to describe it in words.

The first picture shows all the items from minecraft. Remember at the very end the subject "stripped_oak_log"
![image](https://user-images.githubusercontent.com/45980309/193453258-26637795-8619-4452-aa83-405bdb7d8105.png)

After moving to the second page, the next item, for some reason, became "stripped_birch_log", although the list should go to "stripped_spruce_log", which is shown in the picture below from creative inventory
![image](https://user-images.githubusercontent.com/45980309/193453308-9f200da8-eb82-44af-baa8-65371826ec92.png)

creative inventory
![image](https://user-images.githubusercontent.com/45980309/193453386-584ea2a7-e5b2-458d-b0e1-e400eb819c64.png)

It turns out that "stripped_spruce_log" is in the list, but it is not displayed to the player. My guess is that this item replaces some other item.

It is possible that this bug refers to the first case.
But in any case, I do not understand why this is happening and why it's my fault

3. The third bug is that I can get items that are not allowed. These are forward and backward switches. If you visit one of the arrows with the mouse, and then quickly and a lot press any key from the quick access (1-9), then it will go to the player's inventory in the quick slot zone

**Comment by Rysefoxx** [comment] 2022-10-02 18:49
1) In the code you sent me above, as I said, the error is because you say int size = pagination.inventory().size(contents). If the player opens the inventory 1 time, the inventory is 9x6. If the player opens the next page, the init area is called again, but since on the next page the inventory is only 9x2, the #endPosition will make the last item on page 1 be on slot 17. Then he goes to the 2 page and continues there. That's why it happens that the items are duplicated.

2) Should be fixed in 1.5.1.
3) This is probably because when you open a new inventory, the InventoryClickEvent doesn't react for the very small period of time and that's why you can take the items out. Should be fixed in 1.5.1.

**Comment by Rysefoxx** [comment] 2022-10-03 17:23
[Changelog v1.5.1](https://github.com/Rysefoxx/RyseInventory/releases/tag/v1.5.1). If errors occur please create a new TIcket.

**Closed by Rysefoxx** 2022-10-03 17:23 UTC
